public static void primitivesExercise() {
        //You do this part Manisha!

        //1.  Declare three primitives variables, an Integer, a String and a Decimal
        Integer i;
        String str;
        Decimal d;
       
        

        //2.  Assign values to your three new variables
        i = 13;
        str = "Code for Manisha";
        d = 45.3;

        //3.  Print out your variables to the debug log
        system.debug ("IntegerValue is : " +i);
        system.debug ("Stringvalue is : " +str);
        system.debug ("DecimalValue is  : " +d);

        //4.  Declare an integer variable and assign a value in the same line
        
        integer int = 34;
        

        //5.  Print out your integer to the debug log
        
        system.debug ("My IntegerValue is  : " +int);
        

    }
